= The Lady or the Tiger?

== Grammar

----
start -> NAME OBJECT_LIST PREDICATE_LIST RULE_SECTION
NAME -> name: TEXT
OBJECT_LIST -> OBJECT | OBJECT OBJECT_LIST
OBJECT -> object ID: ID_LIST
ID_LIST -> ID | ID ID_LIST
PREDICATE_LIST -> PREDICATE | PREDICATE PREDICATE_LIST
PREDICATE -> predicate ID(ID_LIST)
RULE_SECTION -> rules: RULE_LIST
RULE_LIST -> RULE | RULE RULE_LIST
RULE -> EXPRESSION
EXPRESSION -> TERM | TERM and EXPRESSION | TERM or EXPRESSION | TERM => EXPRESSION | TERM <=> EXPRESSION
TERM -> (EXPRESSION) | !EXPRESSION | APPLIED_PREDICATE | for every ID ID (EXPRESSION) | there is a ID ID (EXPRESSION) | for every ID ID except ID (EXPRESSION) | there is a ID ID except ID (EXPRESSION) | solvable if (EXPRESSION) is known
APPLIED_PREDICATE -> ID(ID_LIST)
----

== First Day

Each of the two rooms can contain either a lady or a tiger.

=== The First Trial

1. In this room there is a lady, and in the other room there is a tiger.
2. In one of these rooms there is a lady, and in one of these rooms there is a tiger.

One sign is true and the other is false.

include::lady1.txt[indent=4]

=== The Second Trial

1. At least one of these rooms contains a lady.
2. A tiger is in the other room.

The statements are either both true or both false.

include::lady2.txt[indent=4]

=== The Third Trial

1. Either a tiger is in this room or a lady is in the other room.
2. A lady is in the other room.

Does the first room contain a lady or a tiger? What about the other room?

include::lady3.txt[indent=4]

== The Second Day

In room 1, if a lady is in it, then the sign on the door is true, but if a tiger is in it, the sign is false. In room 2, the situation is the opposite. Again, there is a lady or a tiger behind each door.

=== The Fourth Trial

1. Both rooms contain ladies.
2. Both rooms contain ladies.

include::lady4.txt[indent=4]

=== The Fifth Trial

1. At least one room contains a lady.
2. The other room contains a lady.

include::lady5.txt[indent=4]

=== The Sixth Trial

1. It makes no difference which room you pick.
2. There is a lady in the other room.

include::lady6.txt[indent=4]

=== The Seventh Trial

1. It does make a difference which room you pick.
2. You are better off choosing the other room.

include::lady7.txt[indent=4]

=== The Eighth Trial

* This room contains a tiger.
* Both rooms contain tigers.

It is not known which sign goes on which door.

include::lady8.txt[indent=4]

== The Third Day

There are three rooms. In only one there is a lady. In the other two there are tigers.

=== The Ninth Trial

1. A tiger is in this room.
2. A lady is in this room.
3. A tiger is in room 2.

At most one of the three signs is true.

include::lady9.txt[indent=4]

=== The Tenth Trial

The sign on the door of the room containing the lady was true, and that at least one of the other two signs was false.

1. A tiger is in room 2.
2. A tiger is in this room.
3. A tiger is in room 1.

include::lady10.txt[indent=4]

=== First, Second, and Third Choice

One of the three rooms contains a lady, another a tiger and the third room was empty.
The sign on the door of the room containing the lady was true.
The sign on the door of the room with the tiger was false.
The sign on the empty room could be true or false.

1. Room 3 is empty.
2. The tiger is in room 1.
3. This room is empty.

include::lady11.txt[indent=4]

== The Fourth Day

=== A Logical Labyrinth

Only one room contains a lady. Each of the other rooms contains either a tiger or is empty.
The sign on the door of the room containing the lady was true.
The signs on the doors of the rooms with the tigers were false.
The signs on the empty rooms could be true or false.

1. The lady is in an odd-numbered room.
2. This room is empty.
3. Either sign 5 is right or sign 7 is wrong.
4. Sign 1 is wrong.
5. Either sign 2 or sign 4 is right.
6. Sign 3 is wrong.
7. The lady is not in room 1.
8. This room contains a tiger and room 9 is empty.
9. This room contains a tiger and 6 is wrong.

This problem is unsolvable, but knowing if room 8 is empty or not is enough to make the problem solvable.

include::lady12.txt[indent=4]
